<?php

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\field\Entity\FieldStorageConfig;
/**
 * Implematation of hook_form_alter

 */ 

function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if($form_id == 'comment_comment_form'){
  	$form['actions']['submit']['#value'] = t('Comment');
  }
}



  function mymodule_allowed_values_function(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
     $options = [
    'left' => 'Left',
    'right' => 'Right',
  ];
    return $options;
  }
